### ISSUE TITLE
Right encoder

### ISSUE THREAD

**Issue by Kooza25** [mxmxmx/O_C#88]
My right encoder only become reverse when I reboot the module.
If in calibration I correct the direction it works good untile reboot.
Already tried to reflash the teensy

**Comment by patrickdowling** [comment]
Did you save the calibration? That'd be the simplest explanation.
If yes, are the other values restored correctly?

**Comment by Kooza25** [comment]
Of course it’s saved and out voltages remain calibrated
Il 31 lug 2019, 12:19 +0200, Patrick Dowling <notifications@github.com>, ha scritto:

**Comment by def1** [comment]
hey . i had the same on mine , tho cant really remember how it got fixed. i also recalibrated a few times after that it was gone i think.

**Comment by patrickdowling** [comment]
Yeah, superficially it doesn't make sense since all the calibration data is saved in the same struct so it's a bit thin to base theories off. IIRC that part hasn't changed in years and if it were systematic it should be more apparent.

What hardware, software version? Does inverting the left encoder in calibration work after a reboot?

**Comment by Kooza25** [comment]
Good input! After inverting left one too, it saved the right and so it does when putting them back to the right direction.
Problem solved, for now
Il 31 lug 2019, 19:09 +0200, Patrick Dowling <notifications@github.com>, ha scritto:
